### ISSUE TITLE
No longer working in Sublime Text 4

### ISSUE THREAD

**Issue by rubjo** [alanJaouen/sublimeGitMoji#5]
Hi, thanks for making this - could the 1.1.0 release have broken something in ST4?

<img width="1708" alt="Skjermbilde 2021-11-15 kl  07 36 36" src="https://user-images.githubusercontent.com/42270947/141733879-dcf2cd81-1e07-47c6-9b89-b188102f98c3.png">

**Comment by alanJaouen** [comment]
Hi, thanks for reporting
I juste released a fix

let me know if it's working on your side

**Comment by rubjo** [comment]
👍🏻 Working nicely again. Thanks!
